### PR TITLE
Adding 9.16.0 for August. Easylist version 202008181203.

### PR DESCRIPTION
**Pull request by ericrobinso**

### CODE REVIEW

**Comment by jkarlin** [comment]
Please add the easylist version number to your commit message.

**Comment by ericrobinso** [comment]
Sorry, you can delete this request.  I forgot the symlink as well, so going to add that then re-request the pull

**Comment by ericrobinso** [comment]
Nevermind, I can't in any way that's obvious in git change the symlinks, and it looks like testing is pointing to 9.13 right now anyway...

**Comment by ericrobinso** [comment]
Updated, it's two commits, but the second has the easylist and symlink.  If you want me to flatten, I can.

**Comment by jkarlin** [comment]
Can you also add the easylist number into the title of this PR? Thanks!

**Pull request merged**
